"""add status field

Revision ID: a5edf90fddbb
Revises: 02f8cc481196
Create Date: 2025-01-24 00:45:23.218301

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5edf90fddbb"
down_revision = "02f8cc481196"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum(
                    "in_progress",
                    "sent",
                    "paid",
                    name="statusenum",
                    native_enum=False,
                    length=36,
                ),
                server_default="in_progress",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("time_created", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("time_updated", sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f("ix_claims_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_status"))
        batch_op.drop_column("time_updated")
        batch_op.drop_column("time_created")
        batch_op.drop_column("status")

    # ### end Alembic commands ###
